apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: weboapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: charitha1202/app:latest
        ports:
        - containerPort: 8085